// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB3KH03BMIPHfM2i3i-vZ1H4HgC4nRliM',
    appId: '1:23048387455:web:dd35ad4588de77bbb2384a',
    messagingSenderId: '23048387455',
    projectId: 'newproject-37196',
    authDomain: 'newproject-37196.firebaseapp.com',
    storageBucket: 'newproject-37196.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkZ2rkvWZm0Pvm3MIGVUbj0arzBI-fTs',
    appId: '1:23048387455:android:0a25883cdade2f8db2384a',
    messagingSenderId: '23048387455',
    projectId: 'newproject-37196',
    storageBucket: 'newproject-37196.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn0k6BHCWj_VJHFDx2ygPvGY29nhOw4YA',
    appId: '1:23048387455:ios:25d0a4093b0d408bb2384a',
    messagingSenderId: '23048387455',
    projectId: 'newproject-37196',
    storageBucket: 'newproject-37196.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn0k6BHCWj_VJHFDx2ygPvGY29nhOw4YA',
    appId: '1:23048387455:ios:25d0a4093b0d408bb2384a',
    messagingSenderId: '23048387455',
    projectId: 'newproject-37196',
    storageBucket: 'newproject-37196.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB3KH03BMIPHfM2i3i-vZ1H4HgC4nRliM',
    appId: '1:23048387455:web:c2d8111c0b93a787b2384a',
    messagingSenderId: '23048387455',
    projectId: 'newproject-37196',
    authDomain: 'newproject-37196.firebaseapp.com',
    storageBucket: 'newproject-37196.firebasestorage.app',
  );
}
